title: Leonhard Lass
author:
  name: Leonhard Lass
  email: 'leo@depart.at'
metadata:
    description: 'Leonhard Lass is a visual artist, designer and lecturer dealing with generative design, generative arts, interface design'

summary:
  enabled: true                             # enable or disable summary of page
  format: short                             # long = summary delimiter will be ignored; short = use the first occurrence of delimiter or size
  size: 120                                 # Maximum length of summary (characters)
  delimiter: ===                            # The summary delimiter 